modified:   .DS_Store
git rm    .ipynb_checkpoints/alias-2421-checkpoint.sh
git rm    .ipynb_checkpoints/alias-2431-checkpoint.sh
git rm    .ipynb_checkpoints/alias-basic-checkpoint.sh
git rm    .ipynb_checkpoints/alias-burning-checkpoint.sh
git rm    .ipynb_checkpoints/alias-checkpoint.sh
git rm    .ipynb_checkpoints/alias-kisti-checkpoint.sh
git rm    .ipynb_checkpoints/alias-mac-checkpoint.sh
git rm    .ipynb_checkpoints/alias-nersc-checkpoint.sh
git rm    .ipynb_checkpoints/autosub-checkpoint.py
git rm    .ipynb_checkpoints/autosub-checkpoint.sh
git rm    .ipynb_checkpoints/autosub-qe-checkpoint.sh
git rm    .ipynb_checkpoints/backup-checkpoint.sh
git rm    .ipynb_checkpoints/cell2xyz-checkpoint.py
git rm    .ipynb_checkpoints/cep-checkpoint.sh
git rm    .ipynb_checkpoints/cep-sol-checkpoint.sh
git rm    .ipynb_checkpoints/cep_ccel-checkpoint.py
git rm    .ipynb_checkpoints/clone-checkpoint.sh
git rm    .ipynb_checkpoints/cobi-checkpoint.py
git rm    .ipynb_checkpoints/cohp-checkpoint.py
git rm    .ipynb_checkpoints/conti-checkpoint.sh
git rm    .ipynb_checkpoints/ediff-checkpoint.sh
git rm    .ipynb_checkpoints/gather-checkpoint.sh
git rm    .ipynb_checkpoints/get-checkpoint.sh
git rm    .ipynb_checkpoints/jobname-checkpoint.sh
git rm    .ipynb_checkpoints/magmom-checkpoint.py
git rm    .ipynb_checkpoints/merge-csvs-checkpoint.py
git rm    .ipynb_checkpoints/modify-checkpoint.sh
git rm    .ipynb_checkpoints/multiple-checkpoint.sh
git rm    .ipynb_checkpoints/neb-checkpoint.sh
git rm    .ipynb_checkpoints/nelect-checkpoint.sh
git rm    .ipynb_checkpoints/pomass-checkpoint.sh
git rm    .ipynb_checkpoints/queue-checkpoint.sh
git rm    .ipynb_checkpoints/rename-checkpoint.sh
git rm    .ipynb_checkpoints/restart-checkpoint.sh
git rm    .ipynb_checkpoints/resub-checkpoint.sh
git rm    .ipynb_checkpoints/rotate-checkpoint.py
git rm    .ipynb_checkpoints/run-burning-checkpoint.sh
git rm    .ipynb_checkpoints/run-kisti-checkpoint.sh
git rm    .ipynb_checkpoints/seawater-checkpoint.sh
git rm    .ipynb_checkpoints/send-checkpoint.sh
git rm    .ipynb_checkpoints/spread-checkpoint.sh
git rm    .ipynb_checkpoints/sub-checkpoint.sh
git rm    .ipynb_checkpoints/te-checkpoint.sh
git rm    .ipynb_checkpoints/temp-checkpoint.sh
git rm    .ipynb_checkpoints/vivi-checkpoint.sh
git rm    .ipynb_checkpoints/walltime-checkpoint.sh
git rm    .ipynb_checkpoints/z-average-checkpoint.py
git rm    .ipynb_checkpoints/z-cation-checkpoint.py
git rm    .ipynb_checkpoints/z-hydrogen-checkpoint.py
git rm    .ipynb_checkpoints/z-minimum-checkpoint.py
git rm    rmpt.py
git rm    run-burning.py
